### ISSUE TITLE
NoTouchID doesn't work on latest Mojave releases (10.14.3 18D109)

### ISSUE THREAD

**Issue by FallenChromium** [al3xtjames/NoTouchID#1]
So I guess the title tells it all. I'm using MBP15,2 SMBIOS and it doesn't help when login windows are appearing, there is same ugly delay and lag. Shame, as it was working perfectly good on 10.13.6 and AFAIK it helped on 10.14.1 too.

**Comment by al3xtjames** [comment]
I cannot reproduce this here (MBP14,3, 10.14.3).

**Comment by FallenChromium** [comment]
Maybe I can help with some kind of logs? I can do this but I need to know what is needed

**Comment by al3xtjames** [comment]
There are no logs (this is a very simple plugin). Try rebuilding your dyld shared cache: `sudo update_dyld_shared_cache -force`
