### ISSUE TITLE
Deprecated ?

### ISSUE THREAD

**Issue by Mateo1234454545** [al3xtjames/NoTouchID#6]
Is this kext still needed for avoiding lag before password verification ?
While on HS and Mojave without it there was a noticeable lag, on Big Sur and latest version of Catalina there is not.

**Comment by al3xtjames** [comment]
Haven't tried 11 yet, but the lag does seem to be gone on 10.15.7.

**Comment by kecinzer** [comment]
I also didn’t notice any lag on Catalina and Big Sur with MacBookPro15,4 SMBIOS.
